"""Add ApiKey model

Revision ID: 4af6105b31a8
Revises: 2b7175c923df
Create Date: 2025-11-22 19:31:01.469357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af6105b31a8'
down_revision = '2b7175c923df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApiKey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ApiKey', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ApiKey_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ApiKey', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ApiKey_key'))

    op.drop_table('ApiKey')
    # ### end Alembic commands ###
